### ISSUE TITLE
Improve error message when attempting to run eDNA flow on .gz files

### ISSUE THREAD

**Issue by vwishingrad** [mhoban/eDNAFlow#22] opened 2023-09-15 01:29 UTC
If a user attempts to (incorrectly) run the analysis on .gz files, it will. not return an error indicating the issue with compressed files. This could be a welcome addition.

**Comment by vwishingrad** [comment] 2023-09-15 06:44
Or maybe if the user tries to run on .gz files, gunzip them automatically and provide a message?

**Comment by mhoban** [comment] 2023-09-19 23:18
This is essentially a duplicate of #11, which will be resolved shortly by supporting gzipped files.

**Closed** 2023-09-19 23:19 UTC
Labels: duplicate
